/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuariosController;
import javax.swing.JOptionPane;



/**
 *
 * @author NICOLAS
 */
public class RegistrarC extends javax.swing.JFrame {
    private UsuariosController userCon;
    /**
     * Creates new form RegistrarC
     */
    public RegistrarC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etEdad = new javax.swing.JTextField();
        etDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etGenero = new javax.swing.JTextField();
        etCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(243, 243, 243));
        setMinimumSize(new java.awt.Dimension(779, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(811, 700));
        setSize(new java.awt.Dimension(650, 650));

        body.setBackground(new java.awt.Color(243, 243, 243));
        body.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        body.setMinimumSize(new java.awt.Dimension(811, 598));
        body.setLayout(null);

        btnGuardar.setBackground(new java.awt.Color(172, 78, 233));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        body.add(btnGuardar);
        btnGuardar.setBounds(417, 530, 95, 31);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        body.add(btnCancelar);
        btnCancelar.setBounds(298, 530, 99, 31);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Genero");
        body.add(jLabel7);
        jLabel7.setBounds(438, 392, 180, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Cedula");
        body.add(jLabel3);
        jLabel3.setBounds(53, 392, 120, 32);

        etEdad.setForeground(new java.awt.Color(102, 102, 102));
        etEdad.setText("Escriba la edad del cliente aqui.");
        etEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etEdadMouseClicked(evt);
            }
        });
        etEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etEdadActionPerformed(evt);
            }
        });
        body.add(etEdad);
        etEdad.setBounds(438, 320, 320, 40);

        etDireccion.setForeground(new java.awt.Color(102, 102, 102));
        etDireccion.setText("Escriba la direccion del cliente aqui.");
        etDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etDireccionMouseClicked(evt);
            }
        });
        etDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etDireccionActionPerformed(evt);
            }
        });
        body.add(etDireccion);
        etDireccion.setBounds(53, 320, 320, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Direccion:");
        body.add(jLabel6);
        jLabel6.setBounds(53, 282, 120, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Edad");
        body.add(jLabel8);
        jLabel8.setBounds(438, 282, 180, 32);

        etNombre.setForeground(new java.awt.Color(102, 102, 102));
        etNombre.setText("Escriba el nombre del cliente aqui.");
        etNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etNombreMouseClicked(evt);
            }
        });
        etNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNombreActionPerformed(evt);
            }
        });
        body.add(etNombre);
        etNombre.setBounds(53, 210, 320, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");
        body.add(jLabel4);
        jLabel4.setBounds(53, 172, 93, 32);

        etCorreo.setForeground(new java.awt.Color(102, 102, 102));
        etCorreo.setText("Escriba el correo del cliente aqui.");
        etCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etCorreoMouseClicked(evt);
            }
        });
        etCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCorreoActionPerformed(evt);
            }
        });
        body.add(etCorreo);
        etCorreo.setBounds(438, 210, 320, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Correo:");
        body.add(jLabel5);
        jLabel5.setBounds(438, 172, 110, 32);

        jLabel1.setBackground(new java.awt.Color(243, 243, 243));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Cliente");
        body.add(jLabel1);
        jLabel1.setBounds(2, 50, 807, 64);

        etGenero.setForeground(new java.awt.Color(102, 102, 102));
        etGenero.setText("Escriba (1) masculino (0) femenino");
        etGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etGeneroMouseClicked(evt);
            }
        });
        etGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etGeneroActionPerformed(evt);
            }
        });
        etGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etGeneroKeyTyped(evt);
            }
        });
        body.add(etGenero);
        etGenero.setBounds(438, 430, 320, 40);

        etCedula.setForeground(new java.awt.Color(102, 102, 102));
        etCedula.setText("Escriba la cedula del cliente aqui");
        etCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etCedulaMouseClicked(evt);
            }
        });
        etCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCedulaActionPerformed(evt);
            }
        });
        body.add(etCedula);
        etCedula.setBounds(53, 430, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void etNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNombreActionPerformed

    private void etCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCorreoActionPerformed

    private void etDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etDireccionActionPerformed

    private void etEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etEdadActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Verificamos que ningun campo este vacio
        if (!etNombre.getText().equals("") && !etCorreo.getText().equals("") && !etDireccion.getText().equals("") && !etEdad.getText().equals("") &&  !etGenero.getText().equals("")&& !etCedula.getText().equals("")) {
            Boolean check = userCon.añadirUsuario(
                    1,
                    Integer.parseInt(etEdad.getText()),
                    Integer.parseInt(etGenero.getText()),
                    etNombre.getText(),
                    etCorreo.getText(),
                    etDireccion.getText(),
                    Integer.parseInt(etCedula.getText())
                   
            );

            if (check) {
                this.dispose();
                JOptionPane.showMessageDialog(null, "Cliente registrado!");
            } else {
                JOptionPane.showMessageDialog(this, "No se registro el cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void etNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etNombreMouseClicked
        etNombre.setText(null);
    }//GEN-LAST:event_etNombreMouseClicked

    private void etCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etCorreoMouseClicked
        etCorreo.setText(null);
    }//GEN-LAST:event_etCorreoMouseClicked

    private void etDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etDireccionMouseClicked
        etDireccion.setText(null);
    }//GEN-LAST:event_etDireccionMouseClicked

    private void etEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etEdadMouseClicked
        etEdad.setText(null);
    }//GEN-LAST:event_etEdadMouseClicked

    private void etGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etGeneroMouseClicked
        etGenero.setText(null);
    }//GEN-LAST:event_etGeneroMouseClicked

    private void etGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etGeneroActionPerformed

    }//GEN-LAST:event_etGeneroActionPerformed

    private void etGeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etGeneroKeyTyped
        if (etGenero.getText().length()== 1) 
         evt.consume();
    }//GEN-LAST:event_etGeneroKeyTyped

    private void etCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etCedulaMouseClicked
        etCedula.setText(null);
    }//GEN-LAST:event_etCedulaMouseClicked

    private void etCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCedulaActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField etCedula;
    private javax.swing.JTextField etCorreo;
    private javax.swing.JTextField etDireccion;
    private javax.swing.JTextField etEdad;
    private javax.swing.JTextField etGenero;
    private javax.swing.JTextField etNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    /**
     * @param userCon the userCon to set
     */
    public void setUserCon(UsuariosController userCon) {
        this.userCon = userCon;
    }
}
